#!/bin/bash

echo -e "\n\033[91mРекомендуем установить библиотеку SFML если её нет!!!\033[0m\n"

# создадим папку где будет весь проект, за одно проверим, есть ли она в директории
if mkdir build
then
	echo "False!"
else
	echo "True!"
fi

# Дадим знать, что надо будет установить библиотеку
cat downloaderSFML/downloadSFML

echo -e "\n\033[94mустанавливаю...\033[0m\n"

# Соберу проект
echo "Начинаю сборку"
if cmake .. && make
then
	cp -a texture/ build/
	echo -e "\n\033[92mПапки с текстурами успешно перенесены в директорию с run-фалом\033[0m \n"
fi

clear

# После сборки дадим пользователю спросить, хочет ли он сыграть в неё сыграть?
echo -e "\033[92mВаша игра собрана, запустить её?\033[0m"
read -p "Y/N : " answer

clear

# exec 0<&6
case $answer in
y) echo -e "Приятной игры)\n" && cd build && ./MyGame;;
n) echo "Ну ладно, потом как нибудь. ";;
esac